### ISSUE TITLE
potential memory leak in dense matrix

### ISSUE THREAD

**Issue by odinthenerd** [halbux/sparselizard#11]
if a valvec is provided which is too small an exception can be thrown [here](https://github.com/halbux/sparselizard/blob/master/src/densematrix.cpp#L39) thus leaking myvaluesptr.

**Comment by halbux** [comment]
Hello, I appreciate your prompt bug report after the talk and am always happy to get bug reports (and I mean it really, even if this was more with the purpose of finding bugs).

I fully understand your issue but although I try to put error messages at as many places as possible I cannot force the user to do things that make sense... if a user wants to provide 3 values to a larger (say a 4x4 densematrix) he might have to realize that this is not an input that makes sense and he should instead provide a vector with 16 values.

It is unfortunately not possible to be behind each user to make sure they do things that make sense.

Regards,

Alexandre
