### ISSUE TITLE
possible performance enhancement by using make_shared

### ISSUE THREAD

**Issue by odinthenerd** [halbux/sparselizard#12]
using make_shared rather than constructing a shared_pointer and newing into its constructor can be a performance enhancement due to locality of objects on the heap as well as saving an allocation. Its also more idiomatic with modern C++ and would save some potential memory leaks.

**Comment by halbux** [comment]
Ok, that's now very constructive and really apprciated! It is duly noted and will take effect from now on in the coming developments.

Regards,

Alexandre

**Comment by odinthenerd** [comment]
actually come to think of it the way you are using shared_ptr is actually not valid as shared_ptr uses delete rather than delete[] which is needed for arrays, see [here](https://stackoverflow.com/questions/13061979/shared-ptr-to-an-array-should-it-be-used) for a better description

**Comment by odinthenerd** [comment]
as a quick fix, you could just add a custom deleter. something like
```
std::shared_ptr<float> ptr(new float[100000], [](float* ptr){ delete[] ptr;} ); 
```
(above code is not tested)

**Comment by bangerth** [comment]
shared_ptr has a specialization for array typed. You have to write the pointer as `shared_ptr<double[]>`.

**Comment by odinthenerd** [comment]
I think shared_ptr<T[]> is a C++17 feature and this is a c++11 library

**Comment by bangerth** [comment]
Ah, true. But it works for `std::unique_ptr`, which is likely what you want to use anyway for arrays of numbers (which you likely don't want to share between objects).
