### ISSUE TITLE
PETSc error when using 'adapt()' and '.setorder' is greater than one

### ISSUE THREAD

**Issue by caseyjamesdavis** [halbux/sparselizard#39]
Hi Alex,

I have been learning how to use the adaptive mesh refinement (AMR) and I ran into this while running the **amr-1d2d3d** example.

![image](https://user-images.githubusercontent.com/49321778/109819975-91a1a200-7c02-11eb-871b-e75eea1d31fd.png)

The problem appears to be isolated to the 2D portion of the example.

If I change the following lines:

```
v.setorder(s1, 5);
v.setorder(s2, 4);
v.setorder(s3, 3);
v.setorder(s4, 3);
```
to:

```
v.setorder(s1, 1);
v.setorder(s2, 1);
v.setorder(s3, 1);
v.setorder(s4, 1);
```
the error goes away and the example runs as expected.

I noticed this first in another simulation I'm working on where the temperature field was set to order 2 and `adapt()` would give the same error.  If I reduced the order of the temperature field to 1 the simulation would work as expected.

Any ideas?

Casey

ps - i did a full re-install this morning.  cjd.

**Comment by halbux** [comment]
Hi Casey,

Another user has had similar issues on a windows compilled petsc. I call a matrix permutation operation of petsc when the order is >1 which seems to be here again the culprit. (when order = 1 operations are straightforward and you will not get that error, that's normal).
Could you send me your main.cpp file (and possibly the mesh as well) to be sure?

**Comment by halbux** [comment]
BTW: I see you are using libopenblas from /usr/lib...: did you install openblas from the repo? I strongly recommend not, it can be extremely slow. Best is to let petsc download it and compile it

**Comment by caseyjamesdavis** [comment]
I'm using Manjaro 20.2.1 and a 5.9 kernel.

The only thing I did was run the 'install_petsc.sh' scripts.  I did not change any settings.

**Comment by halbux** [comment]
Ok. It works on my fedora 30 though (it's part of the examples I run to validate the code every day).
I'll have a closer look asap.

**Comment by halbux** [comment]
Could you please confirm that the error happens during the call 

A.permute(renumtodiagblocks, renumtodiagblocks);

in src/field/rawfield.cpp (or at least another permute call there).

If yes can you also confirm the call happens during the call to 

MatPermute

in src/formulation/mat.cpp

Thanks

**Comment by caseyjamesdavis** [comment]
Happy to help.

Not exactly sure how to check.  Do I run the main.cpp as usual with some kind of debug flag?

**Comment by halbux** [comment]
You could edit the src code to print out a message before the call and after, recompile then run.

Alternatively you could assume that the error comes from there, in which case you could try to add before the MatPermute call

IsSetPermutation(isobject) for the 2 IS objects.

Might also be needed in src/formulation/vec.cpp in the similar permute function.

This might solve your issue.

**Comment by caseyjamesdavis** [comment]
Thanks.  Got it.  I'll add the print statements to your code and let you know what I find.

**Comment by halbux** [comment]
I just checked the petsc main branch and it seems 22 hours ago they changed the behavior of  MatPermute to throw the erro you see, so I will have that error with a fresh enough petsc version. I will fix it now , or tomorrow latest

**Comment by caseyjamesdavis** [comment]
I did get the same error with a petsc/sparselizard install date of 2021/02/04.

**Comment by halbux** [comment]
should be fixed, could you git pull and try again?
Output should be 
1.33227e-15 3.26364e-11 1.35181e-12
with a 1 returned

**Comment by caseyjamesdavis** [comment]
I added the two print statements to src/field/rawfield.cpp:
![image](https://user-images.githubusercontent.com/49321778/109835555-4b077400-7c11-11eb-9034-13392f04b64e.png)

And added the two print statements to src/formulation/mat.cpp
![image](https://user-images.githubusercontent.com/49321778/109835672-6d998d00-7c11-11eb-8db2-eefa12720246.png)

Results:
![image](https://user-images.githubusercontent.com/49321778/109835840-9752b400-7c11-11eb-9851-b1765ccea1fa.png)

**Comment by caseyjamesdavis** [comment]
No problem.  I reinstall and try again.

**Comment by halbux** [comment]
hm, just git pull, you can keep the petsc as it is :)

**Comment by caseyjamesdavis** [comment]
thanks.  I was wondering if that would work.

**Comment by caseyjamesdavis** [comment]
Nice work -  no error ;-)  See results below.

Is it normal for it to take about 15 seconds to transition from the 2D to 3D example?

![image](https://user-images.githubusercontent.com/49321778/109837659-66737e80-7c13-11eb-8bb5-d80e837c6e92.png)

**Comment by halbux** [comment]
Yes it's not surprising it takes at least a couple of seconds, the mesh adaptation is the visible part of the work that is done, but behind the scene the fields must be automatically reinterpolated on the new mesh (here an order 4 curvature mesh with order 5 interpolation fields).

**Comment by caseyjamesdavis** [comment]
That makes sense.  I'll explore the two options you mention.  

Thanks for digging into this so swiftly.

Cheers,
Casey

**Comment by halbux** [comment]
.noautomaticupdate is generally what you want to use for linear static problems. For transient resolutions you cannot use that since the field value at the previous time step (and therefore probably previous mesh) is needed.

Alex
