### ISSUE TITLE
Extra points getting written to .vtu files?

### ISSUE THREAD

**Issue by caseyjamesdavis** [halbux/sparselizard#40]
Hi Alex,

When using the following code :
![image](https://user-images.githubusercontent.com/49321778/111007129-1eafce00-835c-11eb-89cb-5d41bea7627a.png)

Sparselizard correctly reports that there are 5 nodes and 4 elements:
![image](https://user-images.githubusercontent.com/49321778/111000952-f7073880-8350-11eb-9375-6ea1e99be430.png)

When I open the .vtu file in Paraview it reports 8 nodes or points and 4 elements:
![image](https://user-images.githubusercontent.com/49321778/111001094-29b13100-8351-11eb-90b7-0998934f18f2.png)

Inside the .vtu file there appears to be double reporting of the internal points and also the scalar of 3.14 that was written to the mesh.
![image](https://user-images.githubusercontent.com/49321778/111001771-603b7b80-8352-11eb-820e-cd3fbce27c0b.png)

A similar thing happens in 2D if the shape is switched from "line" to "quadrangle":
![image](https://user-images.githubusercontent.com/49321778/111003543-56ffde00-8355-11eb-9276-ae424484bb7d.png)

Sparselizard reports correctly:
![image](https://user-images.githubusercontent.com/49321778/111002975-4bf87e00-8354-11eb-948d-bec301c7bd93.png)

Paraview reports many extra points.
![image](https://user-images.githubusercontent.com/49321778/111003055-6a5e7980-8354-11eb-93e9-6946245eea35.png)

Using the paraview filter 'clean to grid' appears to remove the extra points.

Any ideas?

Cheers,
Casey

[main.cpp.txt](https://github.com/halbux/sparselizard/files/6133504/main.cpp.txt)

**Comment by caseyjamesdavis** [comment]
Here is my code if that helps any.
[main.cpp.txt](https://github.com/halbux/sparselizard/files/6133495/main.cpp.txt)

**Comment by halbux** [comment]
Hi Casey, that's normal behavior w.r.t what I wrote. I ll jave a look at it if I can indeed avoir that. But in any case I should be able to store expressions that are discontinuous between elements, therefore I will have to check if I can still allow that without the duplicated points in the paraview file (in gmsh .pos for example I really need it).

Alex

**Comment by halbux** [comment]
After a quick look it seems to me the duplicates are needed for the piecewise continuous case.

Try saving grad(T).write where T has a jump in slope at a mesh node.

Alex

**Comment by caseyjamesdavis** [comment]
Hi Alex,

I had wondered if it was the result of some other function.  I will experiment with grad(T).write.

Thanks for taking the time to investigate and explain.

Casey
