### ISSUE TITLE
Latest release: Not compatible with petsc 3.17

### ISSUE THREAD

**Issue by Drinausaur** [halbux/sparselizard#61]
This is not valid for petsc 3.17 which is now released, and is the default in the AUR.
3.16.3 cannot be easily installed on Arch anymore.

( in `src/mesh/petscmesh.cpp` )

```
    if (isvalidext)
    {
        #if PETSC_VERSION_GE(3, 16, 3)
            DMPlexCreateFromFile(PETSC_COMM_SELF, filename.c_str(), gentools::getfilename(filename).c_str(), PETSC_TRUE, &mypetscmesh);
        #else
            DMPlexCreateFromFile(PETSC_COMM_SELF, filename.c_str(), PETSC_TRUE, &mypetscmesh);
        #endif
        DMGetDimension(mypetscmesh, &meshdim);
        return;
    }
```

Apparently petsc 3.17 should use the same line as 3.16.3

**Comment by halbux** [comment]
It compiles with the newest petsc from theur main branch, I tested today. What's not correct?

**Comment by Drinausaur** [comment]
This is the error I get when building the AUR package:

```
/home/fabien/.cache/yay/sparselizard/src/sparselizard-v.2021.11/src/mesh/petscmesh.cpp: In constructor ‘petscmesh::petscmesh(std::string)’:
/home/fabien/.cache/yay/sparselizard/src/sparselizard-v.2021.11/src/mesh/petscmesh.cpp:40:65: error: cannot convert ‘PetscBool’ to ‘const char*’
   40 |         DMPlexCreateFromFile(PETSC_COMM_SELF, filename.c_str(), PETSC_TRUE, &mypetscmesh);
      |                                                                 ^~~~~~~~~~
      |                                                                 |
      |                                                                 PetscBool
In file included from /home/fabien/.cache/yay/sparselizard/src/sparselizard-v.2021.11/src/mesh/petscmesh.h:17,
                 from /home/fabien/.cache/yay/sparselizard/src/sparselizard-v.2021.11/src/mesh/petscmesh.cpp:1:
/opt/petsc/linux-c-opt/include/petscdmplex.h:191:74: note:   initializing argument 3 of ‘PetscErrorCode DMPlexCreateFromFile(MPI_Comm, const char*, const char*, PetscBool, _p_DM**)’
  191 | PETSC_EXTERN PetscErrorCode DMPlexCreateFromFile(MPI_Comm, const char[], const char[], PetscBool, DM *);
      |                                                                          ^~~~~~~~~~~~

```

The 3.17 version uses the `plexname[]` argument :
https://gitlab.com/petsc/petsc/-/blob/v3.17.0/src/dm/impls/plex/plexcreate.c#L4671

So I suppose the
```#if PETSC_VERSION_GE(3, 16, 3)```
line should be replaced with
``` #if PETSC_VERSION_GE(3, 16, 3) or 3.17```

**Comment by halbux** [comment]
I ll check on Monday. Or merge your PR before that if you can check until then

**Comment by Drinausaur** [comment]
Ok, I think I understand what happened.

sparselizard master does certainly work. But not the latest release ( 2021.11-1 ). ( It does not contain the `#if PETSC_VERSION_GE` line )

The AUR package is set for the latest release.
In order to repair the AUR package, I think we would need a new tag ( so a new sparselizard version ? ) 

@pointhi certainly knows what would be the best option.

( On our side we'll check If sparselizard master still works with our code, as we only tested the release )
 
Don't create a version right now, there could be a better option to repair the AUR package.
Until we repair it, sparselizard cannot be installed using the package.

**Comment by halbux** [comment]
Indeed! And we discussed with @pointhi a new release is needed. Let me know if it works for you as it is now. If yes I ll make a new release. If no I'll fix it then make a release.

**Comment by pointhi** [comment]
@halbux I'm pretty sure we need a new git tag, which then allows me to bump the AUR package version

**Comment by halbux** [comment]
Ok. Will do Monday is possible.

**Comment by halbux** [comment]
@pointhi @Drinausaur  New relase done.

**Comment by pointhi** [comment]
I updated the AUR package: https://aur.archlinux.org/packages/sparselizard
