### ISSUE TITLE
Do not use abort()

### ISSUE THREAD

**Issue by Drinausaur** [halbux/sparselizard#67]
Using `abort()` will crash any software running sparselizard in the same process.
There are over 600 `abort()` calls in the current master.

Using C++ exceptions would allow the host application to catch the problem, without crashing.

**Comment by halbux** [comment]
That's true. I should take the time to change that!

**Comment by halbux** [comment]
Just found the time. Will work on it today. @Drinausaur. Sorry for the delay, it's been hectic.

**Comment by halbux** [comment]
Done @Drinausaur. Sorry for the delay.
